"""
Model diagnostic plots generated by running INFERENCE on the saved weights.
No retraining required - it reuses pytorch/trained_model.pth on the test set.

Produces (into plots/img/):
    confusion_matrix.png      - 10x10 matrix of true vs predicted digit
    per_class_accuracy.png    - accuracy for each digit 0-9
    misclassifications.png    - grid of images the model got wrong (pred vs true)
    learned_filters.png       - the 8 learned 3x3 convolution filters

Currently wired for the PyTorch model (the framework installed in this env).
The same structure works for the NumPy / TensorFlow models once those
environments are available - swap the model-loading / forward section.

Run:  python plot_diagnostics.py   (from inside the plots/ directory)
"""
import os
import sys
import numpy as np
from _style import apply_style
import matplotlib.pyplot as plt

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.join(HERE, "..")
PT = os.path.join(ROOT, "pytorch")
OUT = os.path.join(HERE, "img")
os.makedirs(OUT, exist_ok=True)
apply_style()

# Import the PyTorch model + data helpers from the pytorch/ package.
sys.path.insert(0, PT)
import torch
from network import MNIST
from data import load_and_prep_data

# train.py saves to its run directory; the committed weights live at repo root.
WEIGHTS = os.path.join(ROOT, "trained_model.pth")
TEST_CSV = os.path.join(ROOT, "mnist_test", "mnist_test.csv")


def load_model():
    model = MNIST()
    model.load_state_dict(torch.load(WEIGHTS, map_location="cpu", weights_only=True))
    model.eval()
    return model


def run_inference(model):
    X, Y = load_and_prep_data(TEST_CSV)
    X_t = torch.tensor(X, dtype=torch.float32)
    y_true = np.asarray(Y).argmax(axis=1)

    preds = []
    with torch.no_grad():
        for i in range(0, X_t.shape[0], 256):
            logits = model(X_t[i:i + 256])
            preds.append(logits.argmax(dim=1).numpy())
    y_pred = np.concatenate(preds)
    # First conv layer weights, shape (8, 1, 3, 3)
    filters = model.conv1.weight.detach().numpy()
    return X, y_true, y_pred, filters


def plot_confusion_matrix(y_true, y_pred):
    cm = np.zeros((10, 10), dtype=int)
    for t, p in zip(y_true, y_pred):
        cm[t, p] += 1

    fig, ax = plt.subplots(figsize=(7.5, 6.5))
    ax.grid(False)
    im = ax.imshow(cm, cmap="Blues")
    fig.colorbar(im, ax=ax, fraction=0.046, pad=0.04, label="count")
    ax.set_xticks(range(10)); ax.set_yticks(range(10))
    ax.set_xlabel("Predicted digit"); ax.set_ylabel("True digit")
    ax.set_title("PyTorch Confusion Matrix (test set)",
                 fontsize=13, fontweight="bold")
    thresh = cm.max() / 2
    for t in range(10):
        for p in range(10):
            v = cm[t, p]
            if v:
                ax.text(p, t, str(v), ha="center", va="center", fontsize=8,
                        color="white" if v > thresh else "black")
    path = os.path.join(OUT, "confusion_matrix.png")
    fig.savefig(path, bbox_inches="tight"); plt.close(fig)
    print("wrote", path)
    return cm


def plot_per_class_accuracy(cm):
    per_class = cm.diagonal() / cm.sum(axis=1) * 100
    fig, ax = plt.subplots(figsize=(8.5, 5))
    bars = ax.bar(range(10), per_class, color="#4C72B0", edgecolor="white")
    for b, v in zip(bars, per_class):
        ax.annotate(f"{v:.1f}", (b.get_x() + b.get_width() / 2, v),
                    textcoords="offset points", xytext=(0, 3),
                    ha="center", fontsize=8)
    ax.set_xticks(range(10))
    ax.set_xlabel("Digit"); ax.set_ylabel("Accuracy (%)")
    ax.set_ylim(min(per_class) - 1.5, 100.3)
    ax.set_title("PyTorch Per-Class Accuracy", fontsize=13, fontweight="bold")
    path = os.path.join(OUT, "per_class_accuracy.png")
    fig.savefig(path, bbox_inches="tight"); plt.close(fig)
    print("wrote", path)


def plot_misclassifications(X, y_true, y_pred, n=15):
    wrong = np.where(y_true != y_pred)[0][:n]
    cols = 5
    rows = int(np.ceil(len(wrong) / cols))
    fig, axes = plt.subplots(rows, cols, figsize=(cols * 1.8, rows * 1.9))
    fig.suptitle("PyTorch Misclassifications  (pred / true)",
                 fontsize=13, fontweight="bold")
    for ax in axes.flat:
        ax.axis("off")
    for ax, idx in zip(axes.flat, wrong):
        ax.imshow(X[idx, 0], cmap="gray")
        ax.set_title(f"{y_pred[idx]} / {y_true[idx]}", fontsize=10,
                     color="#C44E52")
    path = os.path.join(OUT, "misclassifications.png")
    fig.savefig(path, bbox_inches="tight"); plt.close(fig)
    print("wrote", path)


def plot_learned_filters(filters):
    n = filters.shape[0]
    fig, axes = plt.subplots(2, (n + 1) // 2, figsize=((n + 1) // 2 * 1.6, 3.4))
    fig.suptitle("Learned 3x3 Convolution Filters (conv1)",
                 fontsize=13, fontweight="bold")
    for ax in axes.flat:
        ax.axis("off")
    for ax, i in zip(axes.flat, range(n)):
        ax.imshow(filters[i, 0], cmap="viridis")
        ax.set_title(f"filter {i}", fontsize=9)
    path = os.path.join(OUT, "learned_filters.png")
    fig.savefig(path, bbox_inches="tight"); plt.close(fig)
    print("wrote", path)


def plot_activation_maps(model, X, y_true, digit=None):
    # Pick one clean sample of the requested digit (default: first image).
    if digit is None:
        idx = 0
    else:
        idx = int(np.where(y_true == digit)[0][0])
    sample = torch.tensor(X[idx:idx + 1], dtype=torch.float32)

    # Run the sample through the network stage by stage to grab activations.
    with torch.no_grad():
        conv = model.conv1(sample)            # (1, 8, 26, 26)
        relu = model.relu(conv)               # after non-linearity
        pooled = model.maxpool(relu)          # (1, 8, 13, 13)
    relu = relu[0].numpy()
    pooled = pooled[0].numpy()
    n = relu.shape[0]  # 8 channels

    # Rows: [input], conv+relu maps (8), maxpool maps (8).
    fig = plt.figure(figsize=(n * 1.5, 5.2))
    gs = fig.add_gridspec(2, n + 1, hspace=0.35, wspace=0.1)

    ax0 = fig.add_subplot(gs[:, 0])
    ax0.imshow(X[idx, 0], cmap="gray")
    ax0.set_title(f"input\n(digit {y_true[idx]})", fontsize=10)
    ax0.axis("off")

    for c in range(n):
        ax = fig.add_subplot(gs[0, c + 1])
        ax.imshow(relu[c], cmap="viridis")
        ax.axis("off")
        if c == 0:
            ax.set_ylabel("conv+relu", fontsize=9)
        ax.set_title(f"ch {c}", fontsize=8)

        ax = fig.add_subplot(gs[1, c + 1])
        ax.imshow(pooled[c], cmap="viridis")
        ax.axis("off")

    fig.suptitle("Activation maps through Conv -> ReLU (top) -> MaxPool (bottom)",
                 fontsize=13, fontweight="bold")
    # Row labels via figure text.
    fig.text(0.13, 0.70, "conv+relu\n26x26", ha="right", va="center", fontsize=9)
    fig.text(0.13, 0.30, "maxpool\n13x13", ha="right", va="center", fontsize=9)

    path = os.path.join(OUT, "activation_maps.png")
    fig.savefig(path, bbox_inches="tight")
    plt.close(fig)
    print("wrote", path)


if __name__ == "__main__":
    model = load_model()
    X, y_true, y_pred, filters = run_inference(model)
    acc = (y_true == y_pred).mean() * 100
    print(f"Test accuracy: {acc:.2f}%")
    cm = plot_confusion_matrix(y_true, y_pred)
    plot_per_class_accuracy(cm)
    plot_misclassifications(X, y_true, y_pred)
    plot_learned_filters(filters)
    plot_activation_maps(model, X, y_true, digit=7)
